=== rena2henriques/OOP/simulation.dtd
<!ELEMENT simulation (grid,initialpoint,finalpoint,specialcostzones,obstacles,events)>
<!ATTLIST simulation finalinst CDATA #REQUIRED>
<!ATTLIST simulation initpop CDATA #REQUIRED>
<!ATTLIST simulation maxpop CDATA #REQUIRED>
<!ATTLIST simulation comfortsens CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid colsnb CDATA #REQUIRED>
<!ATTLIST grid rowsnb CDATA #REQUIRED>
<!ELEMENT initialpoint EMPTY>
<!ATTLIST initialpoint xinitial CDATA #REQUIRED>
<!ATTLIST initialpoint yinitial CDATA #REQUIRED>
<!ELEMENT finallpoint EMPTY>
<!ATTLIST finallpoint xfinal CDATA #REQUIRED>
<!ATTLIST finallpoint yfinal CDATA #REQUIRED>
<!ELEMENT specialcostzones (zone+)>
<!ATTLIST specialcostzones num CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone xinitial CDATA #REQUIRED>
<!ATTLIST zone yinitial CDATA #REQUIRED>
<!ATTLIST zone xfinal CDATA #REQUIRED>
<!ATTLIST zone yfinal CDATA #REQUIRED>
<!ELEMENT obstacles (obstacle+)>
<!ELEMENT obstacle EMPTY>
<!ATTLIST obstacle xpos CDATA #REQUIRED>
<!ATTLIST obstacle ypos CDATA #REQUIRED>
<!ELEMENT events (death,reproduction,move)>
<!ELEMENT death EMPTY>
<!ATTLIST death param CDATA #REQUIRED>
<!ELEMENT reproduction EMPTY>
<!ATTLIST reproduction param CDATA #REQUIRED>
<!ELEMENT move EMPTY>
<!ATTLIST move param CDATA #REQUIRED>

=== rena2henriques/OOP/XMLexamples/test_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation SYSTEM "simulation.dtd"> 
<simulation finalinst="100" initpop="10" maxpop="500" comfortsens="3"> 
   <grid colsnb="10" rowsnb="10"/> 
   <initialpoint xinitial="2" yinitial="1"/> 
   <finalpoint xfinal="10" yfinal="9"/>
   <specialcostzones num="1">
      <zone xinitial="8" yinitial="8" xfinal="5" yfinal="5">3</zone>
   </specialcostzones>
   <obstacles num="15">
      <obstacle xpos="1" ypos="5"/>
      <obstacle xpos="3" ypos="5"/>
      <obstacle xpos="4" ypos="5"/>
      <obstacle xpos="6" ypos="5"/>
      <obstacle xpos="6" ypos="4"/>
      <obstacle xpos="6" ypos="3"/>
      <obstacle xpos="6" ypos="2"/>
      <obstacle xpos="6" ypos="1"/>
      <obstacle xpos="6" ypos="8"/>
      <obstacle xpos="6" ypos="9"/>
      <obstacle xpos="6" ypos="10"/>
      <obstacle xpos="7" ypos="8"/>
      <obstacle xpos="9" ypos="8"/>
      <obstacle xpos="10" ypos="8"/>
   </obstacles>
   <events>
      <death param="10"/>
      <reproduction param="1"/>
      <move param="1"/>
   </events>
</simulation>

=== rena2henriques/OOP/test_zigzag.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation SYSTEM "simulation.dtd"> 
<simulation finalinst="100" initpop="10" maxpop="500" comfortsens="3"> 
   <grid colsnb="10" rowsnb="2"/> 
   <initialpoint xinitial="1" yinitial="1"/> 
   <finalpoint xfinal="10" yfinal="2"/>
   <obstacles num="5">
      <obstacle xpos="1" ypos="2"/>
      <obstacle xpos="3" ypos="1"/>
      <obstacle xpos="5" ypos="2"/>
      <obstacle xpos="7" ypos="1"/>
      <obstacle xpos="9" ypos="2"/>
   </obstacles>
   <events>
      <death param="10"/>
      <reproduction param="1"/>
      <move param="1"/>
   </events>
</simulation>
